[workspace]
members = [ "build/salva2d", "build/salva3d" ]

[profile.release]
#lto = true
#codegen-units = 1

[patch.crates-io]
ncollide2d = { path = "../ncollide-dev/build/ncollide2d" }
ncollide3d = { path = "../ncollide-dev/build/ncollide3d" }
nphysics2d = { path = "../nphysics-dev/build/nphysics2d" }
nphysics3d = { path = "../nphysics-dev/build/nphysics3d" }